m3lib = $(ROOT)/$(CMAQ_DIRNAME)
dest = $(m3lib)/pario_gcc8.3.0

fc = mpif90

ioapi = $(IOAPI_DIR)/ioapi/fixed_src
fflags = -O2 -ffixed-line-length-132 -fbacktrace -fallow-argument-mismatch -fno-automatic \
 -I$(ioapi) -I.

libname = libpario.a

VPATH=.:src:

objs = \
 pinterpb_mod.o \
 piomaps_mod.o \
 alloc_data_mod.o \
 boundary.o \
 get_write_map.o \
 growbuf.o \
 gtndxhdv.o \
 interpol.o \
 pinterpb.o \
 pio_init.o \
 pio_re_init.o \
 pm3err.o \
 pm3exit.o \
 pm3warn.o \
 pshut3.o \
 pwrite3.o \
 ptrwrite3.o \
 pwrgrdd.o \
 readbndy.o \
 subdmap.o \
 wrsubmap.o

.SUFFIXES: .f

$(libname): $(objs)
	ar -rv $@ $(objs)
	chmod 644 $@
	rm $(objs)
	mkdir -p $(dest)
	mv *.mod $(dest)
	mv $(libname) $(dest)
.f.o:
	$(fc) $(fflags) -c $<
