m3lib = $(HOME)/pkg/cmaq/4.7.1/lib
dest = $(m3lib)/stenex/noop_pgi

fc = pgf90
fstd = -O2 -Mextend -traceback -Msave #-tp=istanbul

VPATH=.:src:

objects = \
 noop_comm_module.o \
 noop_data_copy_module.o \
 noop_gather_module.o \
 noop_global_max_module.o \
 noop_global_min_module.o \
 noop_global_sum_module.o \
 noop_init_module.o \
 noop_term_module.o \
 noop_slice_module.o \
 noop_util_module.o \
 noop_modules.o

modules = \
 noop_comm_module.mod \
 noop_data_copy_module.mod \
 noop_gather_module.mod \
 noop_global_max_module.mod \
 noop_global_min_module.mod \
 noop_global_sum_module.mod \
 noop_init_module.mod \
 noop_modules.mod \
 noop_slice_module.mod \
 noop_term_module.mod \
 noop_util_module.mod \

lib = libsef90_noop.a

.SUFFIXES: .f

$(lib): $(objects)
	ar rsv $(lib) $(objects)
	chmod 444 $(lib)
	rm $(objects)
	mkdir -p $(dest)
	mv $(lib) $(dest)
	mv $(modules) $(dest)

.f.o:
	$(fc) -c $(fstd) $<
