#! /apps/python/2.7.6/bin/python2.7

import sys
from netCDF4 import Dataset
import numpy as np

if len(sys.argv) != 3:
   print 'incorrect args: must be forcing_path & nlays_frc'
   sys.exit(1)
try:
   f_data = Dataset(sys.argv[1], 'r')
except:
   print 'unable to read', sys.argv[1]
   exit(1)
try:
   nlays = int(sys.argv[2])
except:
   print sys.argv[2], 'not recognised as int'
   exit(1)

# BEGIN USER INPUT SECTION
var_name = 'CO2'
# END USER INPUT SECTION

try:
   fgrid = f_data.variables[var_name]
except:
   print var_name, 'not found in', sys.argv[1]
   exit(1)

if len(fgrid.shape) != 4:
   print 'file has wrong set of dimensions'
   exit(1)

t, l, r, c = fgrid.shape

if l < nlays:
   print 'file has only', l, 'layers. requested', nlays
   exit(1)
elif l > nlays:
   if np.sum(fgrid[:, nlays:, :, :]) > 0:
      print 'forcing file has data beyond requested layer', nlays
      exit(1)

exit(0)